services:
  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    depends_on:
      - db
    ports:
     - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=volkovlabs-form-panel, https://github.com/CorpGlory/grafana-progress-list/archive/v1.0.9.zip;corpglory-progresslist-panel
  db:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dbpassword}
      POSTGRES_DB: ${DB_NAME:-db}
      POSTGRES_USER: ${DB_USER:-dbuser}
    volumes:
      - db:/var/lib/postgresql/data
  db-ui:
    # image: adminer
    image: ghcr.io/shyim/adminerevo
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - ${ADMINER_PORT:-8888}:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=dracula
volumes:
  grafana:
  db: