{
 "title": "Store Activity",
 "time": { "from": "2024-04-20T00:00:00.000Z", "to": "2024-07-20T00:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "selected_store_id", "label": "Store ID", "query": "SELECT id FROM stores" }
  ]
 },
 "panels": [
  {
   "title": "Store Activity",
   "type": "timeseries",
   "description": "Active ordered per day",
   "gridPos": { "h": 16, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroupAlias(created_at, '1d'),\r\n  COUNT(number) AS ordered,\r\n  order_limit,\r\n  capacity\r\nFROM orders \r\nJOIN stores ON stores.id = store_id\r\nWHERE store_id = $selected_store_id\r\nGROUP BY time, order_limit, capacity"
    }
   ]
  },
  {
   "title": "Store Location",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM stores\r\nWHERE id = $selected_store_id"
    }
   ]
  },
  {
   "title": "Active Orders Grid",
   "type": "table",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  number,\r\n  status,\r\n  anonymous_id,\r\n  ROUND(price / 100.00, 2)::float AS price,\r\n  created_at,\r\n  updated_at,\r\n  shiped_at,\r\n  collected_at\r\nFROM orders\r\nWHERE store_id = $selected_store_id\r\nORDER BY updated_at DESC"
    }
   ]
  }
 ]
}