{
 "title": "Customer Orders",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "anonymous_id",
    "query": "SELECT anonymous_id FROM customers"
   }
  ]
 },
 "panels": [
  {
   "title": "Customer orders",
   "type": "table",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  number AS \"order number\",\r\n  status,\r\n  created_at AS created,\r\n  completed_at AS completed\r\nFROM orders \r\nWHERE $__timeFilter(orders.created_at) AND anonymous_id = '$anonymous_id'"
    }
   ]
  },
  {
   "title": "Stores",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  lat,\r\n  lon,\r\n  name,\r\n  COUNT(stores.id) AS count\r\nFROM orders \r\nJOIN stores ON orders.store_id = stores.id AND lat IS NOT NULL\r\nWHERE $__timeFilter(created_at)\r\n  AND anonymous_id = '$anonymous_id'\r\nGROUP BY \r\n  lat,\r\n  lon,\r\n  name"
    }
   ]
  },
  {
   "title": "Сustomer Purchases",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  product_key,\r\n  sku,\r\n  name,\r\n  quantity,\r\n  line_items.created_at AS \"added at\",\r\n  category,\r\n  section,\r\n  color,\r\n  'https://cdn.media.amplience.net/i/primarktest/991102718560_01' AS image_url,\r\n  CONCAT('https://www.primark.com/', LOWER(orders.locale), '/p/', products.slug) as pdp\r\nFROM line_items\r\nJOIN products ON product_key = key\r\nJOIN orders ON line_items.order_number = orders.number AND orders.anonymous_id = '$anonymous_id'\r\nWHERE $__timeFilter(orders.created_at)\r\nORDER BY line_items.updated_at"
    }
   ]
  }
 ]
}