{
 "title": "General",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "accuracy", "query": "1d,7d,1h,6h,12h" }
  ]
 },
 "panels": [
  {
   "title": "Orders dynamics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "db",
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"createdAt\", $interval),\r\n  COUNT(number) as \"order qty\"\r\nFROM orders\r\nWHERE $__timeFilter(\"createdAt\")\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Order events dynamics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "db",
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"createdAt\", $interval),\r\n  COUNT(orderNumber) as 'confirmed'\r\nFROM events\r\nWHERE $__timeFilter(\"createdAt\")\r\n  AND type = 'confirmed'\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "dataset": "db",
     "rawSql": "SELECT\r\n  $__timeGroupAlias(createdAt, $interval),\r\n  COUNT(orderNumber) as 'payment pending'\r\nFROM events\r\nWHERE $__timeFilter(createdAt)\r\n  AND type = 'payment-pending'\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "dataset": "db",
     "rawSql": "SELECT\r\n  $__timeGroupAlias(createdAt, $interval),\r\n  COUNT(orderNumber) as 'dispatched'\r\nFROM events\r\nWHERE $__timeFilter(createdAt)\r\n  AND type = 'dispatched'\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "dataset": "db",
     "rawSql": "SELECT\r\n  $__timeGroupAlias(createdAt, $interval),\r\n  COUNT(orderNumber) as 'collected'\r\nFROM events\r\nWHERE $__timeFilter(createdAt)\r\n  AND type = 'collected'\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "dataset": "db",
     "rawSql": "SELECT\r\n  $__timeGroupAlias(createdAt, $interval),\r\n  COUNT(orderNumber) as 'returned'\r\nFROM events\r\nWHERE $__timeFilter(createdAt)\r\n  AND type = 'returned'\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Orders by day",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "db",
     "rawSql": "SELECT \r\nDATE(\"createdAt\") AS date,\r\nCOUNT(\"number\") as qty\r\nFROM orders\r\nWHERE $__timeFilter(\"createdAt\")\r\nGROUP BY date"
    }
   ]
  },
  {
   "title": "Order status countgers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db",
     "rawSql": "SELECT\r\n  COUNT(\"orderNumber\") as 'confirmed'\r\nFROM events\r\nWHERE $__timeFilter(\"createdAt\")\r\n  AND type = 'confirmed'"
    },
    {
     "dataset": "db",
     "rawSql": "SELECT\r\n  COUNT(orderNumber) as 'payment-pending'\r\nFROM events\r\nWHERE $__timeFilter(\"createdAt\")\r\n  AND type = 'payment-pending'"
    },
    {
     "dataset": "db",
     "rawSql": "SELECT\r\n  COUNT(orderNumber) as 'dispatched'\r\nFROM events\r\nWHERE $__timeFilter(createdAt)\r\n  AND type = 'dispatched'"
    },
    {
     "dataset": "db",
     "rawSql": "SELECT\r\n  COUNT(orderNumber) as 'collected'\r\nFROM events\r\nWHERE $__timeFilter(createdAt)\r\n  AND type = 'collected'"
    },
    {
     "dataset": "db",
     "rawSql": "SELECT\r\n  COUNT(orderNumber) as 'returned'\r\nFROM events\r\nWHERE $__timeFilter(createdAt)\r\n  AND type = 'returned'"
    }
   ]
  },
  {
   "title": "Average time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "db",
     "rawSql": "SELECT \r\n  #*\r\n  SUBSTRING(SEC_TO_TIME(AVG(CASE WHEN type = 'confirmed' THEN TIME_TO_SEC(`diff`) END)), 1, 8) as 'confirmed -> payment-pending',\r\n  SUBSTRING(SEC_TO_TIME(AVG(CASE WHEN type = 'payment-pending' THEN TIME_TO_SEC(`diff`) END)), 1, 8) as 'payment-pending -> dispatched',\r\n  SUBSTRING(SEC_TO_TIME(AVG(CASE WHEN type = 'dispatched' THEN TIME_TO_SEC(`diff`) END)), 1, 8) as 'dispatched -> collected'\r\nFROM (\r\n  SELECT *, \r\n    SEC_TO_TIME(TIMESTAMPDIFF(SECOND, createdAt, LEAD(createdAt) OVER (ORDER BY orderNumber))) AS diff\r\n  FROM (\r\n    SELECT * FROM events \r\n    WHERE $__timeFilter(createdAt) AND type IN ('confirmed', 'payment-pending', 'dispatched', 'collected') \r\n    ORDER BY orderNumber LIMIT 10) as events\r\n) as events\r\nWHERE type IN ('confirmed', 'payment-pending', 'dispatched')\r\n#GROUP BY type"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "db",
     "rawSql": "SELECT \r\nCOUNT(*) as \"finished orders\"\r\nFROM \"orderEvents\"\r\nWHERE type = 'completed'"
    },
    {
     "dataset": "db",
     "rawSql": "SELECT \r\nCOUNT(*) as \"returned orders\"\r\nFROM \"orderEvents\"\r\nWHERE type = 'pendingRefund'"
    }
   ]
  }
 ]
}