{
 "title": "Active Orders",
 "description": "Orders are being processed",
 "time": { "from": "2024-07-07T16:33:21.215Z", "to": "2024-07-21T19:44:00.937Z" },
 "panels": [
  {
   "title": "Active Orders Statuses",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE completed_at IS NULL\r\n  AND created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status = 'created'\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE completed_at IS NULL\r\n  AND created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status = 'paymentPending'\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE completed_at IS NULL\r\n  AND created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status = 'confirmed'\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE completed_at IS NULL\r\n  AND created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status IN ('shipment', 'shipmentFailed')\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE completed_at IS NULL\r\n  AND created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status IN ('dispatched', 'dispatchFailed')\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE completed_at IS NULL\r\n  AND created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status IN ('paymentPendingCapture', 'wmsOrderConfirmationFailed')\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE completed_at IS NULL\r\n  AND created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status = 'unfulfilled'\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE completed_at IS NULL\r\n  AND created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status IN ('readyToCollect', 'readyToCollectPartially')\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE completed_at IS NULL\r\n  AND created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status = 'collected'\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE completed_at IS NULL\r\n  AND created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status = 'returnCreated'\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE completed_at IS NULL\r\n  AND created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status = 'pendingRefund'\r\nGROUP BY status"
    }
   ]
  },
  {
   "title": "Active Orderds Timeline",
   "type": "timeseries",
   "description": "Accuracy = 3 hours",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(created_at, '3h'),\r\n  COUNT(number) as created\r\nFROM orders\r\nWHERE created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status = 'created'\r\nGROUP BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(created_at, '3h'),\r\n  COUNT(number) as paymentPending\r\nFROM orders\r\nWHERE created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status = 'paymentPending'\r\nGROUP BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(created_at, '3h'),\r\n  COUNT(number) as confirmed\r\nFROM orders\r\nWHERE created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status = 'confirmed'\r\nGROUP BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(created_at, '3h'),\r\n  COUNT(number) as shipment\r\nFROM orders\r\nWHERE created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status IN ('shipment', 'shipmentFailed')\r\nGROUP BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(created_at, '3h'),\r\n  COUNT(number) as dispatched\r\nFROM orders\r\nWHERE created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status IN ('dispatched', 'dispatchFailed')\r\nGROUP BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(created_at, '3h'),\r\n  COUNT(number) as paymentPendingCapture\r\nFROM orders\r\nWHERE created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status IN ('paymentPendingCapture', 'wmsOrderConfirmationFailed')\r\nGROUP BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(created_at, '3h'),\r\n  COUNT(number) as unfulfilled\r\nFROM orders\r\nWHERE created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status = 'unfulfilled'\r\nGROUP BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(created_at, '3h'),\r\n  COUNT(number) as readyToCollect\r\nFROM orders\r\nWHERE created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status IN ('readyToCollect', 'readyToCollectPartially')\r\nGROUP BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(created_at, '3h'),\r\n  COUNT(number) as collected\r\nFROM orders\r\nWHERE created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status = 'collected'\r\nGROUP BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(created_at, '3h'),\r\n  COUNT(number) as returnCreated\r\nFROM orders\r\nWHERE created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status = 'returnCreated'\r\nGROUP BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(created_at, '3h'),\r\n  COUNT(number) as pendingRefund\r\nFROM orders\r\nWHERE created_at > NOW() - INTERVAL '2 WEEKS' \r\n  AND status = 'pendingRefund'\r\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Active Orders Grid",
   "type": "table",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  number,\r\n  status,\r\n  anonymous_id,\r\n  price / 100 as price,\r\n  store_id,\r\n  created_at,\r\n  updated_at,\r\n  shiped_at,\r\n  collected_at\r\nFROM orders\r\nWHERE completed_at IS NULL\r\n  AND created_at > NOW() - INTERVAL '2 WEEKS'\r\nORDER BY updated_at DESC"
    }
   ]
  }
 ]
}