{
 "title": "Finished Orders",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Order Status Counters",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE $__timeFilter(completed_at) AND status = 'cancelledNoInventory'\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE $__timeFilter(completed_at) AND status = 'paymentAuthFailed'\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE $__timeFilter(completed_at) AND status = 'paymentCaptureFailed'\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE $__timeFilter(completed_at) AND status = 'paymentCanceled'\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE $__timeFilter(completed_at) AND status = 'authorisationCanceled'\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE $__timeFilter(completed_at) AND status = 'authorisationCancelFailed'\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE $__timeFilter(completed_at) AND status = 'dispatchedParcelMismatch'\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE $__timeFilter(completed_at) AND status = 'canceledLostInTransit'\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE $__timeFilter(completed_at) AND status = 'canceled'\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE $__timeFilter(completed_at) AND status = 'refundSuccess'\r\nGROUP BY status"
    },
    {
     "rawSql": "SELECT\r\n  status,\r\n  COUNT(status)\r\nFROM orders\r\nWHERE $__timeFilter(completed_at) AND status = 'refundFailed'\r\nGROUP BY status"
    }
   ]
  },
  {
   "title": "Order Groups",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(created_at, '1d'),\r\n  COUNT(number) as refunded\r\nFROM orders\r\nWHERE $__timeFilter(created_at) AND status = 'refundSuccess'\r\nGROUP BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(created_at, '1d'),\r\n  COUNT(number) as collected\r\nFROM orders\r\nWHERE $__timeFilter(created_at) AND completed_at IS NOT NULL AND status = 'collected'\r\nGROUP BY time\r\n"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(created_at, '1d'),\r\n  COUNT(number) as failed\r\nFROM orders\r\nWHERE $__timeFilter(created_at) AND status IN (\r\n  'authorisationCancelFailed',\r\n  'paymentAuthFailed',\r\n  'paymentCaptureFailed',\r\n  'dispatchedParcelMismatch',\r\n  'canceledLostInTransit',\r\n  'refundFailed'\r\n)\r\nGROUP BY time\r\n"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(created_at, '1d'),\r\n  COUNT(number) as canceled\r\nFROM orders\r\nWHERE $__timeFilter(created_at) AND status IN ('authorisationCanceled', 'canceled', 'cancelledNoInventory', 'paymentCanceled', 'canceledLostInTransit')\r\nGROUP BY time\r\n"
    }
   ]
  },
  {
   "title": "Stores Activity",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 16, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  lat,\r\n  lon,\r\n  COUNT(store_id) AS count\r\nFROM orders \r\nLEFT JOIN stores ON store_id = stores.id\r\nWHERE $__timeFilter(created_at)\r\n  AND completed_at iS NOT NULL\r\n  AND lat IS NOT NULL\r\nGROUP BY \r\n  lat,\r\n  lon\r\n"
    }
   ]
  },
  {
   "title": "Order segmentation",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\r\nCOUNT(*) as delivered\r\nFROM orders\r\nWHERE $__timeFilter(created_at)\r\n  AND completed_at iS NOT NULL\r\n  AND status = 'collected'"
    },
    {
     "rawSql": "SELECT\r\nCOUNT(*) as \"not delivered\"\r\nFROM orders\r\nWHERE $__timeFilter(created_at)\r\n  AND completed_at iS NOT NULL\r\n  AND status != 'collected'"
    }
   ]
  }
 ]
}