{
 "title": "Order Analysis",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "selected_order_number", "label": "Order Number", "query": "SELECT number FROM orders" }
  ]
 },
 "panels": [
  {
   "title": "Order Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "db",
     "rawSql": "SELECT\r\n  status,\r\n  anonymous_id,\r\n  (price::float / 100) AS price,\r\n  store_id::text,\r\n  created_at,\r\n  updated_at,\r\n  collected_at,\r\n  shiped_at\r\nFROM orders\r\nWHERE number = '$selected_order_number'"
    }
   ]
  },
  {
   "title": "Line Items",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  product_key::text,\r\n  sku::text,\r\n  name,\r\n  line_items.price::float / 100 AS price,\r\n  quantity::text,\r\n  line_items.created_at AS \"added at\",\r\n  line_items.updated_at AS \"modified at\",\r\n  category,\r\n  section,\r\n  color,\r\n  'https://cdn.media.amplience.net/i/primarktest/991102718560_01' AS image_url,\r\n  CONCAT('https://www.primark.com/', LOWER(orders.locale), '/p/', products.slug) as pdp\r\nFROM line_items\r\nJOIN products ON product_key = key\r\nJOIN orders ON line_items.order_number = orders.number\r\nWHERE order_number = '$selected_order_number'"
    }
   ]
  },
  {
   "title": "Order Delays",
   "type": "table",
   "description": "Show time delays between order states",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n   type,\r\n   created_at, \r\n   lead(created_at) OVER (ORDER BY created_at) - created_at AS delay\r\nFROM order_events \r\nWHERE order_number = '$selected_order_number'\r\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "Payment Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  json_array_elements(json_array_elements(payload->'payments')->'transactions')->>'timestamp' as timestamp,\r\n  json_array_elements(json_array_elements(payload->'payments')->'transactions')->>'type' as type,\r\n  json_array_elements(json_array_elements(payload->'payments')->'transactions')->>'state' as state,\r\n  json_array_elements(payload->'payments')->>'method' as method\r\nFROM order_events \r\nWHERE type = 'created' AND order_number = '$selected_order_number'\r\n"
    }
   ]
  },
  {
   "title": "Order History",
   "type": "logs",
   "gridPos": { "h": 13, "w": 15, "x": 9, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  type,\r\n  created_at,\r\n  payload\r\nFROM order_events\r\nWHERE order_number = '$selected_order_number'\r\nORDER BY created_at"
    }
   ]
  }
 ]
}