{
 "title": "Order review",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "selectedOrderNumber", "label": "Select order number", "query": "SELECT number FROM orders" }
  ]
 },
 "panels": [
  {
   "title": "Shipment progress",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  sku,\r\n  max(qty) filter (WHERE type = 'confirmed') AS ordered,\r\n  MAX(CASE WHEN type = 'shipment' THEN qty ELSE 0 END) AS shiped\r\nFROM (\r\n  SELECT\r\n    type,\r\n    sku,\r\n    qty\r\n  FROM \"orderEvents\" AS confirmed,\r\n    json_populate_recordset(null::record, payload->'orderItems') AS (sku varchar, qty int)\r\n  WHERE confirmed.\"orderNumber\" = '$selectedOrderNumber' AND type = 'confirmed'\r\n\r\n  UNION \r\n\r\n  SELECT\r\n    type,\r\n    sku,\r\n    qty\r\n  FROM \"orderEvents\" AS shipment,\r\n    json_populate_recordset(null::record, payload) AS (sku varchar, qty int)\r\n  WHERE shipment.\"orderNumber\" = '$selectedOrderNumber' AND type = 'shipment'\r\n)\r\nGROUP BY sku"
    }
   ]
  },
  {
   "title": "Shipment progress",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  sku,\r\n  max(qty) filter (WHERE type = 'confirmed') AS ordered,\r\n  MAX(CASE WHEN type = 'shipment' THEN qty ELSE 0 END) AS shiped\r\nFROM (\r\n  SELECT\r\n    type,\r\n    sku,\r\n    qty\r\n  FROM \"orderEvents\" AS confirmed,\r\n    json_populate_recordset(null::record, payload->'orderItems') AS (sku varchar, qty int)\r\n  WHERE confirmed.\"orderNumber\" = '$selectedOrderNumber' AND type = 'confirmed'\r\n\r\n  UNION \r\n\r\n  SELECT\r\n    type,\r\n    sku,\r\n    qty\r\n  FROM \"orderEvents\" AS shipment,\r\n    json_populate_recordset(null::record, payload) AS (sku varchar, qty int)\r\n  WHERE shipment.\"orderNumber\" = '$selectedOrderNumber' AND type = 'shipment'\r\n)\r\nGROUP BY sku"
    }
   ]
  },
  {
   "title": "Events list",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"type\",\r\n  \"createdAt\", \r\n  delta,\r\n  payload\r\nFROM  (\r\n   SELECT\r\n   \"orderNumber\",\r\n   \"type\",\r\n   \"createdAt\", \r\n   payload,\r\n   lead(\"createdAt\") OVER (ORDER BY \"createdAt\") - \"createdAt\" AS delta\r\n   FROM \"orderEvents\"\r\n   ) t\r\nWHERE \"orderNumber\" = '$selectedOrderNumber'\r\nORDER  BY \"createdAt\""
    }
   ]
  },
  {
   "title": "General info",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  status,\r\n  \"customerRef\",\r\n  \"customerId\",\r\n  \"createdAt\" AS created,\r\n  \"completedAt\" AS \"completed\"\r\nFROM orders\r\nWHERE number = '$selectedOrderNumber'"
    }
   ]
  },
  {
   "title": "Store location",
   "type": "geomap",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"createdAt\",\r\n  name,\r\n  lat,\r\n  lon\r\nFROM \"orderEvents\"\r\nJOIN stores ON stores.id = (payload->>'storeId')::integer\r\nWHERE \"orderNumber\" = '$selectedOrderNumber' AND type = 'created'"
    }
   ]
  },
  {
   "title": "Transactional events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"type\",\r\n  \"createdAt\"\r\nFROM  \"orderEvents\"\r\nWHERE \"orderNumber\" = '$selectedOrderNumber' AND type IN (\r\n  'tInitialized',\r\n  'tInitializeFailed',\r\n  'tCollected',\r\n  'tCollectFailed',\r\n  'tRefunded',\r\n  'tRefundFailed'\r\n  )\r\nORDER  BY \"createdAt\""
    }
   ]
  },
  {
   "title": "Notification events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"type\",\r\n  \"createdAt\"\r\nFROM  \"orderEvents\"\r\nWHERE \"orderNumber\" = '$selectedOrderNumber' AND type IN (\r\n  'emailCancelledLostInTransit',\r\n  'emailCollected',\r\n  'emailCollectionReminder1',\r\n  'emailCollectionReminder2',\r\n  'emailCollectionReminder3',\r\n  'emailLostInTransitPartially',\r\n  'emailOrderConfirmed',\r\n  'emailOrderDispatched',\r\n  'emailOrderDispatchParcelMismatch',\r\n  'emailPaymentCaptureFailed',\r\n  'emailReadyToCollect',\r\n  'emailRefundConfirmation',\r\n  'emailRefundFailure',\r\n  'emailRefundUncollected',\r\n  'emailUnfulfilled'\r\n)\r\nORDER  BY \"createdAt\""
    }
   ]
  }
 ]
}