{
 "title": "SKU review",
 "time": { "from": "2024-03-07T00:00:00.000Z", "to": "2024-06-03T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "selectedSku",
    "label": "SKU",
    "query": "SELECT \n   sku\nFROM\n   \"orderEvents\",\n   json_populate_recordset(null::record, payload->'orderItems') AS (sku varchar)\nWHERE type = 'confirmed'\nGROUP BY sku"
   }
  ]
 },
 "panels": [
  {
   "title": "SKU ordered dymanic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n   $__timeGroupAlias(\"createdAt\", '1d'),\r\n   SUM(qty) as \"ordered qty\"\r\nFROM\r\n   \"orderEvents\",\r\n   json_populate_recordset(null::record, payload->'orderItems') AS (sku varchar, qty int)\r\nWHERE type = 'confirmed' AND sku = '$selectedSku'\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "SKU ordered  by date",
   "type": "table",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n   $__timeGroupAlias(\"createdAt\", '1d'),\r\n   SUM(qty) as \"ordered qty\"\r\nFROM\r\n   \"orderEvents\",\r\n   json_populate_recordset(null::record, payload->'orderItems') AS (sku varchar, qty int)\r\nWHERE type = 'confirmed' AND sku = '$selectedSku'\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Orders with this SKU",
   "type": "table",
   "gridPos": { "h": 17, "w": 5, "x": 8, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n   \"orderNumber\",\r\n   \"createdAt\" AS \"ordered at\"\r\nFROM\r\n   \"orderEvents\",\r\n   json_populate_recordset(null::record, payload->'orderItems') AS (sku varchar, qty int)\r\nWHERE type = 'confirmed' AND sku = '$selectedSku'"
    }
   ]
  },
  {
   "title": "SKU ordered total",
   "type": "stat",
   "gridPos": { "h": 17, "w": 11, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n   $__timeGroupAlias(\"createdAt\", '1d'),\r\n   SUM(qty) as \"ordered qty\"\r\nFROM\r\n   \"orderEvents\",\r\n   json_populate_recordset(null::record, payload->'orderItems') AS (sku varchar, qty int)\r\nWHERE type = 'confirmed' AND sku = '$selectedSku'\r\nGROUP BY time\r\nORDER BY \"ordered qty\""
    }
   ]
  }
 ]
}