{
 "title": "SKU Review",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "selected_sku", "label": "SKU", "query": "SELECT sku FROM skus" }
  ]
 },
 "panels": [
  {
   "title": "SKU Analysis",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  key AS \"product key\",\r\n  name,\r\n  size,\r\n  category,\r\n  section\r\n  color,\r\n  'https://cdn.media.amplience.net/i/primarktest/991102718560_01' AS image_url,\r\n  CONCAT('https://www.primark.com/en-gb/p/', products.slug) as pdp\r\nFROM skus\r\nJOIN products ON products.key = product_key\r\nWHERE sku = $selected_sku\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "SKU Ordered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(created_at, '1d'),\r\n  COUNT(skus.sku) as count\r\nFROM skus\r\nJOIN line_items ON skus.sku = line_items.sku\r\nWHERE \r\n  $__timeFilter(created_at)\r\n  AND skus.sku = $selected_sku\r\nGROUP BY time"
    }
   ]
  },
  {
   "title": "SKU Stocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  created_at,\r\n  available_quantity\r\nFROM line_items\r\nWHERE \r\n  $__timeFilter(created_at)\r\n  AND sku = $selected_sku"
    }
   ]
  }
 ]
}