{
 "title": "Order analysis",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "selectedOrderNumber", "label": "Order Number", "query": "SELECT number FROM orders" }
  ]
 },
 "panels": [
  {
   "title": "Delays",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM  (\r\n   SELECT\r\n   \"orderNumber\",\r\n   \"type\",\r\n   \"createdAt\", \r\n   lead(\"createdAt\") OVER (ORDER BY \"createdAt\") - \"createdAt\" AS delta\r\n   FROM \"orderEvents\"\r\n   ) t\r\nWHERE \"orderNumber\" = '$selectedOrderNumber'\r\nORDER  BY \"createdAt\""
    }
   ]
  },
  {
   "title": "Order timeline",
   "type": "status-history",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "db",
     "rawSql": "SELECT createdAt,\r\n#DATE_ADD(createdAt, INTERVAL 15 second) as nextEvent,\r\n#orderNumber,\r\ntype as 'confirmed'\r\nFROM events\r\nWHERE orderNumber = \"$selectedOrderNumber\" \r\nAND type = 'confirmed'\r\n#ORDER BY createdAt\r\n\r\n# DATE_ADD(createdAt, INTERVAL 15 second) as nextEvent"
    },
    {
     "dataset": "db",
     "rawSql": "SELECT createdAt,\r\ntype as 'payment pending'\r\nFROM events\r\nWHERE orderNumber = \"$selectedOrderNumber\" \r\nAND type = 'payment-pending'"
    },
    {
     "dataset": "db",
     "rawSql": "SELECT createdAt,\r\ntype as 'dispatched'\r\nFROM events\r\nWHERE orderNumber = \"$selectedOrderNumber\" \r\nAND type = 'dispatched'"
    },
    {
     "dataset": "db",
     "rawSql": "SELECT createdAt,\r\ntype as 'collected'\r\nFROM events\r\nWHERE orderNumber = \"$selectedOrderNumber\" \r\nAND type = 'collected'"
    },
    {
     "dataset": "db",
     "rawSql": "SELECT createdAt,\r\ntype as 'returned'\r\nFROM events\r\nWHERE orderNumber = \"$selectedOrderNumber\" \r\nAND type = 'returned'"
    }
   ]
  },
  {
   "title": "Order list",
   "type": "table",
   "gridPos": { "h": 30, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "db",
     "rawSql": "SELECT number as \"order number\", \"createdAt\"\r\nFROM orders\r\nWHERE $__timeFilter(\"createdAt\")"
    }
   ]
  },
  {
   "title": "Email events",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "dataset": "db",
     "rawSql": "\r\n\r\nSELECT \r\n  type, \r\n  createdAt,\r\n  SEC_TO_TIME(TIMESTAMPDIFF(SECOND, createdAt, LEAD(createdAt) OVER (ORDER BY orderNumber))) AS 'time to open'\r\nFROM \r\n  (SELECT \r\n  type,\r\n  createdAt,\r\n  orderNumber\r\n  FROM events\r\n  WHERE type IN('email-send', 'email-open') and orderNumber = \"$selectedOrderNumber\")\r\n  as events\r\nWHERE orderNumber = \"$selectedOrderNumber\""
    }
   ]
  }
 ]
}