{
 "title": "Orders stats",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Order status counters",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  name,\r\n  COUNT(\"eventTypes\".name)\r\nFROM \"eventTypes\"\r\nJOIN orders ON orders.status = \"eventTypes\".name\r\nWHERE $__timeFilter(\"createdAt\")\r\nGROUP BY \"eventTypes\".name"
    },
    {
     "rawSql": "SELECT\r\n  'confirmed',\r\n  COUNT(number)\r\nFROM orders\r\nWHERE $__timeFilter(\"createdAt\")"
    }
   ]
  },
  {
   "title": "Order stats",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"createdAt\", '1d'),\r\n  COUNT(number) as \"refunded\"\r\nFROM orders\r\nWHERE $__timeFilter(\"createdAt\") AND status = 'refundSuccess'\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"createdAt\", '1d'),\r\n  COUNT(number) as \"collected\"\r\nFROM orders\r\nWHERE $__timeFilter(\"createdAt\") AND status = 'collected'\r\nGROUP BY time\r\nORDER BY time\r\n"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"createdAt\", '1d'),\r\n  COUNT(number) as \"failed\"\r\nFROM orders\r\nWHERE $__timeFilter(\"createdAt\") AND status in (\r\n  'cancelFailed',\r\n  'cancelledNoInventory',\r\n  'paymentAuthFailed',\r\n  'paymentCaptureFailed',\r\n  'paymentCanceled',\r\n  'unfulfilled',\r\n  'dispatchedParcelMismatch',\r\n  'canceledLostInTransit',\r\n  'refundFailed'\r\n)\r\nGROUP BY time\r\nORDER BY time\r\n"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(\"createdAt\", '1d'),\r\n  COUNT(number) as \"confirmed\"\r\nFROM orders\r\nWHERE $__timeFilter(\"createdAt\")\r\nGROUP BY time\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "Orders activity",
   "type": "table",
   "gridPos": { "h": 15, "w": 16, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  number,\r\n  status,\r\n  \"customerRef\",\r\n  \"customerId\",\r\n  \"createdAt\",\r\n  \"completedAt\"\r\nFROM orders \r\nWHERE $__timeFilter(\"createdAt\") \r\nORDER BY \"createdAt\"\r\n"
    }
   ]
  },
  {
   "title": "Order segmentation",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\r\nCOUNT(*) as \"refunded\"\r\nFROM orders\r\nWHERE $__timeFilter(\"createdAt\") AND status = 'refundSuccess'"
    },
    {
     "rawSql": "SELECT\r\nCOUNT(*) as \"collected\"\r\nFROM orders\r\nWHERE $__timeFilter(\"createdAt\") AND status = 'collected'\r\n"
    },
    {
     "rawSql": "SELECT\r\nCOUNT(*) as \"failed\"\r\nFROM orders\r\nWHERE $__timeFilter(\"createdAt\") AND status in (\r\n  'cancelFailed',\r\n  'cancelledNoInventory',\r\n  'paymentAuthFailed',\r\n  'paymentCaptureFailed',\r\n  'paymentCanceled',\r\n  'unfulfilled',\r\n  'dispatchedParcelMismatch',\r\n  'canceledLostInTransit',\r\n  'refundFailed'\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Locations",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  stores.lat,\r\n  stores.lon,\r\n  COUNT(stores.id) AS \"count\"\r\nFROM orders \r\nRIGHT JOIN \"orderEvents\" ON orders.number = \"orderEvents\".\"orderNumber\" AND \"orderEvents\".type = 'created'\r\nLEFT JOIN stores ON stores.id = (payload->>'storeId')::integer\r\nWHERE $__timeFilter(orders.\"createdAt\") \r\nGROUP BY stores.id\r\n"
    }
   ]
  }
 ]
}